name: "Build nix package"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Flake check
        run: nix flake check --all-systems
      - name: Build and test
        run: nix build .#bot
